import Head from "next/head";
import { useEffect, useReducer } from "react";
import employeeReducer from "@/state/employeeReducer";
import { initialState, MainContext } from "@/state"; 
import styles from "@/styles/Home.module.scss";
import CardList from "@/components/cardList";
import Header from "@/components/header";
import { IMainContext } from "@/interfaces/IState";
import { IDataHomeProps } from "@/interfaces/IComponentsProps";
export const API_BASE_URL: string = "http://localhost:8080/api/v1/employee";

export default function Home({ employees }: IDataHomeProps) {
  const [state, dispatch] = useReducer(employeeReducer, initialState) as [IMainContext['state'], IMainContext['dispatch']];

  useEffect(() => {
    if (!initialState.data.length)
      dispatch({ type: 'FETCH_SUCCESS', payload: employees });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <>
      <Head>
        <title>Employee manager app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="author" content="Mirko Montaina" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContext.Provider value={{ state, dispatch }}>
      <Header />
      <main className={`${styles.main}`}>
        <section className={styles.content}>
          <div className={styles.container}>
            <CardList employees={ state.data } />
          </div>
        </section>
      </main>
      </MainContext.Provider>
    </>
  );
}

export async function getServerSideProps() {
  try {
    const response = await fetch(`${API_BASE_URL}/all`);
    if (!response.ok) {
      throw new Error('Failed to fetch data');
    }
    const employees = await response.json();
    return {
      props: {employees}
    };
  } catch (error: any) {
    console.error('Error fetching data:', error);
    throw new Error(error.message);
  }
}